version: "3"
services:
   db:
     image: postgres
     environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=password
     ports:
       - "127.0.0.1:5432:5432"
   web:
     build: .
     command:
       - python server/manage.py runserver 0.0.0.0:8000
     volumes:
       - .:/code
     ports:
       - "127.0.0.1:8000:8000"
     depends_on:
       - db