# Generated by Django 3.2.5 on 2021-08-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_remove_comment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='child_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='child_comments',
            field=models.ManyToManyField(null=True, to='comments.Comment'),
        ),
    ]
